---
- block:
  - name: Update conf file daemon.json
    template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json
      owner: centos
      group: centos

  - name: Reload docker
    command: systemctl reload docker
  tags:
    - build
    - preprod
    - prod

